name: DevSecOps Pipeline

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-app:latest .

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: devsecops-app:latest
          format: table
          exit-code: "1"
          severity: "HIGH,CRITICAL"

      - name: Run app container
        run: docker run -d -p 5000:5000 --name app devsecops-app:latest

      - name: ZAP Baseline Scan
        run: |
          docker run --network host -t owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:5000 \
            -r zap-report.html \
            -x zap-report.xml

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap-report.html
            zap-report.xml
